@startuml

!include style.puml
@startuml

!include style.puml
box PKB (From SP)
participant "SP" as SP LOGIC_COLOR
participant “:WriteStorage” as WriteStorage LOGIC_COLOR
participant “:StmtManager" as StmtManager LOGIC_COLOR
participant ":FollowsManager" as FollowsManager LOGIC_COLOR
participant “:PatternManager” as AssignPatternManager LOGIC_COLOR

end box
activate SP

SP -> WriteStorage: getStmtManager()
activate WriteStorage
WriteStorage --> SP: StmtManager
deactivate WriteStorage

SP -> StmtManager: insertEntity(int: stmtNo)
Activate StmtManager
StmtManager --> SP: bool
deactivate StmtManager

SP -> WriteStorage: getFollowsManager()
activate WriteStorage
WriteStorage --> SP: followsManager
deactivate WriteStorage

SP -> FollowsManager: insertRelationship(int: stmtNo, int: stmtNo)
Activate FollowsManager
FollowsManager --> SP: bool
deactivate FollowsManager

SP -> WriteStorage: getAssignPatternManager()
activate WriteStorage
WriteStorage --> SP: assignPatternManager
deactivate WriteStorage

SP -> AssignPatternManager: insertAssignPattern(int: stmtNo, string: left, shared_ptr<ShuntNode>: right)
Activate AssignPatternManager
AssignPatternManager --> SP: bool
deactivate AssignPatternManager

@enduml
