@startuml

!include style.puml
@startuml

!include style.puml
box PKB (To QPS)
participant "QPS" as QPS LOGIC_COLOR
participant “:ReadStorage” as ReadStorage LOGIC_COLOR
participant “:StmtManager" as StmtManager LOGIC_COLOR
participant ":FollowsManager" as FollowsManager LOGIC_COLOR
participant “:AssignPatternManager” as AssignPatternManager LOGIC_COLOR

end box
activate QPS

QPS -> ReadStorage: getStmtManager()
activate ReadStorage
ReadStorage --> QPS: stmtManager
deactivate ReadStorage

QPS -> StmtManager: getAllEntitiesEntries()
Activate StmtManager
StmtManager --> QPS: unordered_set<int>: result
deactivate StmtManager

QPS -> ReadStorage: getFollowsManager()
activate ReadStorage
ReadStorage --> QPS: followsManager
deactivate ReadStorage

QPS -> FollowsManager: getAllRelationshipEntries()
Activate FollowsManager
FollowsManager --> QPS: unordered_map<int, unordered_set<int>>: result
deactivate FollowsManager

QPS -> ReadStorage: getAssignPatternManager()
activate ReadStorage
ReadStorage --> QPS: assignPatternManager
deactivate ReadStorage

QPS -> AssignPatternManager: getAllPatternEntries()
Activate AssignPatternManager
AssignPatternManager --> QPS: unordered_map<int, int>: result
deactivate AssignPatternManager

@enduml
