name: Windows

on:

  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: ["master", "ci-testing"]
  
  workflow_dispatch:
    branches:     
      - "*"

jobs:
  build:
      runs-on: windows-latest
      timeout-minutes: 10
      strategy:
        fail-fast: true

      steps:
        - uses: actions/checkout@v3
        - uses: ilammy/msvc-dev-cmd@v1

        - name: Make Build folder
          run: |
            cd .\Team26\Code26
            mkdir build
            cd build
            cmake -G "Ninja" ..

        - name: Build Project
          run: |
            cd Team26\Code26\build
            cmake --build . --config Release
            cd ../..

        - name: Copy Builds
          run: |
            mkdir artifacts
            cp .\Team26\Code26\build\src\autotester\autotester.exe .\artifacts\autotester.exe
            cp .\Team26\Code26\build\src\unit_testing\unit_testing.exe .\artifacts\unit_testing.exe
            cp .\Team26\Code26\build\src\integration_testing\integration_testing.exe .\artifacts\integration_testing.exe

        - name: Upload Builds
          uses: actions/upload-artifact@v3
          with:
            name: build-artifacts
            path: .\artifacts
            retention-days: 7

  unit-test:
      needs: build
      runs-on: windows-latest
      timeout-minutes: 10
      strategy:
        fail-fast: true
      
      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v3
          with: 
            name: build-artifacts
            path: .\artifacts

        - name: Run Unit Test
          shell: powershell
          timeout-minutes: 1
          run: |
            cd .\artifacts
            .\unit_testing.exe

  integration-test:
      needs: build
      runs-on: windows-latest
      timeout-minutes: 10
      strategy:
        fail-fast: true
      
      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v3
          with: 
            name: build-artifacts
            path: .\artifacts

        - name: Run Intergration Test
          shell: powershell
          timeout-minutes: 1
          run: |
            cd .\artifacts
            .\integration_testing.exe

  autotester-run:
      needs: build
      runs-on: windows-latest
      timeout-minutes: 10
      strategy:
        fail-fast: true
      
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Download build artifacts
          uses: actions/download-artifact@v3
          with: 
            name: build-artifacts
            path: .\artifacts

        - name: Copy Autotester
          run: |
            cp .\artifacts\autotester.exe .\Team26\Tests26

        - name: Run Autotester via script
          run: |
            cd .\Team26\Tests26\testing_tools
            node tester.js

        - name: Save Test Results
          uses: actions/upload-artifact@v3
          with:
            name: autotester-result
            path: .\Team26\Tests26\results
            retention-days: 7
  
  autotester-upload:
      needs: autotester-run
      runs-on: [self-hosted, Windows, X64]
      timeout-minutes: 10
      strategy:
        fail-fast: true

      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Download build artifacts
          uses: actions/download-artifact@v3
          with: 
            name: autotester-result
            path: .\artifacts

        - name: Copy build artifacts
          run: |
            Copy-Item -Path "./artifacts" -Destination "./Team26/Tests26/results" -Force -Recurse

        - name: Install dependepncies
          run: |
            cd .\Team26\Tests26\testing_tools
            npm i

        - name: Copy Key
          run: |
            cd .\Team26\Tests26\testing_tools
            Copy-Item -Path "../../../../../../../../../../keys/keys.json" -Destination "./"
                
        - name: Run uploader
          id: gsheet-uploader
          shell: pwsh
          run: |
            cd .\Team26\Tests26\testing_tools
            node uploader.js ${{ vars.SPREADSHEET_ID }} ${{ vars.STORE_URL }} ${{ github.sha }} 1 >> $env:GITHUB_OUTPUT

        - name: Comment PR
          uses: thollander/actions-comment-pull-request@v2
          if: github.event_name != 'push'
          with:
            message: |
              The autotester result: ${{ steps.gsheet-uploader.outputs.url }}
        

