name: CI for Cmake Project - Windows

on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Run Linter
        run: |
          cd .\Team26\Code26\src\spa
          cpplint --recursive --filter=-legal/copyright,-runtime/references --linelength=120 extensions=cpp,h .
  build:
      runs-on: [self-hosted, Windows, X64]
      timeout-minutes: 10
      strategy:
        fail-fast: true

      steps:
        - uses: actions/checkout@v3
        - name: Build Project
          shell: powershell
          run: |
            cd .\Team26\Code26
            mkdir build
            cd build
            cmake ..
            cmake --build . --target autotester --config Release
            cd ../..