name: CI for Cmake Project - Windows

on:

  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

  push:
    branches: ["master", "ci-testing"]

jobs:
  build:
      runs-on: [self-hosted, Windows, X64]
      timeout-minutes: 10
      strategy:
        fail-fast: true

      steps:
        - uses: actions/checkout@v3

        - name: Make Build folder
          shell: powershell
          run: |
            cd .\Team26\Code26
            mkdir build
            cd build
            cmake -G "Ninja" ..

        - name: Build Project
          shell: powershell
          run: |
            cd Team26\Code26\build
            cmake --build . --config Release
            cd ../..

        - name: Copy Builds
          shell: powershell
          run: |
            mkdir artifacts
            cp .\Team26\Code26\build\src\autotester\autotester.exe .\artifacts\autotester.exe
            cp .\Team26\Code26\build\src\unit_testing\unit_testing.exe .\artifacts\unit_testing.exe
            cp .\Team26\Code26\build\src\integration_testing\integration_testing.exe .\artifacts\integration_testing.exe

        - name: Upload Builds
          uses: actions/upload-artifact@v3
          with:
            name: build-artifacts
            path: .\artifacts
            retention-days: 7

  unit-test:
      needs: build
      runs-on: [self-hosted, Windows, X64]
      timeout-minutes: 10
      strategy:
        fail-fast: true
      
      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v3
          with: 
            name: build-artifacts
            path: .\artifacts

        - name: Run Unit Test
          shell: powershell
          timeout-minutes: 1
          run: |
            cd .\artifacts
            .\unit_testing.exe

        - name: Run Intergration Test
          shell: powershell
          timeout-minutes: 1
          run: |
            cd .\artifacts
            .\integration_testing.exe

  autotester:
      needs: build
      runs-on: [self-hosted, Windows, X64]
      timeout-minutes: 10
      strategy:
        fail-fast: true
      
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Download build artifacts
          uses: actions/download-artifact@v3
          with: 
            name: build-artifacts
            path: .\artifacts

        - name: Copy Autotester
          shell: powershell
          run: |
            cp .\artifacts\autotester.exe .\Team26\Tests26

        - name: Run Autotester via script
          shell: powershell
          run: |
            cd .\Team26\Tests26\testing_tools
            node tester.js

        - name: Install dependepncies
          shell: powershell
          run: |
            cd .\Team26\Tests26\testing_tools
            npm i

        - name: Copy Key
          run: |
            cd .\Team26\Tests26\testing_tools
            Copy-Item -Path "../../../../../../../../../../keys/keys.json" -Destination "./"
                
        - name: Run uploader
          id: gsheet-uploader
          shell: powershell
          run: |
            cd .\Team26\Tests26\testing_tools
            node uploader.js ${{ vars.SPREADSHEET_ID }} >> $GITHUB_OUTPUT

        - name: Comment PR
          uses: thollander/actions-comment-pull-request@v2
          if: github.event_name != 'push'
          with:
            message: |
              The autotester result: ${{ steps.gsheet-uploader.outputs.url }}
        

