name: CI for Cmake Project - Windows

on: [push]

jobs:
  checkstyle:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
          
      - name: Install cpplint
        run: pip install cpplint

      - name: Run Linter
        run: |
          cd Team26/Code26/src/spa
          cpplint --recursive --filter=-legal/copyright,-runtime/references --linelength=120 extensions=cpp,h .


  build:
      runs-on: [self-hosted, Windows, X64]
      timeout-minutes: 10
      strategy:
        fail-fast: true

      steps:
        - uses: actions/checkout@v3

        - name: Restore build cache
          id: cache-build
          uses: actions/cache@v3
          with:
            path: Team26/Code26/build
            key: build-cache

        - name: Make Build folder
          if: steps.cache-build.outputs.cache-hit != 'true'
          shell: powershell
          run: |
            cd .\Team26\Code26
            mkdir build
            cd build
            cmake ..    

        - name: Build Project
          shell: powershell
          run: |
            cd .\Team26\Code26
            cd build
            cmake --build . --target autotester --config Release
            cmake --build . --target unit_testing --config Release
            cd ../..
        
        - name: Run Unit Test
          shell: powershell
          timeout-minutes: 1
          run: |
            cd .\Team26\Code26\build\src\unit_testing\Release\
            .\unit_testing.exe

        # - name: Run Autotester
        #   shell: powershell
        #   timeout-minutes: 1
        #   run: |
        #     cd .\Team26\Code26\build\src\autotester\Release\
        #     .\autotester.exe ..\..\..\..\..\Tests26\Milestone1\Sample_source.txt ..\..\..\..\..\Tests26\Milestone1\Sample_queries.txt ..\..\..\..\..\Tests26\Milestone1\out.xml
        
        # - name: Upload Result
        #   shell: powershell
        #   timeout-minutes: 1  
        #   run: |
        #     cd .\Team26\Code26\build\src\autotester\Release\
        #     mkdir tests
        #     Copy-Item -Path "../../../../../../../../_folder32/uploader.ps1" -Destination "./"
        #     start powershell -ArgumentList "-File .\uploader.ps1 -branchName ${{ github.ref_name }} -sha ${{ github.sha }}"
