name: CI for Cmake Project - Windows

on:

  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

  push:
    branches: ["master", "ci-testing"]

jobs:
  build:
      runs-on: [self-hosted, Windows, X64]
      timeout-minutes: 10
      strategy:
        fail-fast: true

      steps:
        - uses: actions/checkout@v3

        - name: Make Build folder
          shell: powershell
          run: |
            cd .\Team26\Code26
            mkdir build
            cd build
            cmake -G "Ninja" ..

        - name: Build Project
          shell: powershell
          run: |
            cd Team26\Code26\build
            cmake --build . --config Release
            cd ../..
        
        - name: Run Unit Test
          shell: powershell
          timeout-minutes: 1
          run: |
            cd .\Team26\Code26\build\src\unit_testing\
            .\unit_testing.exe

        - name: Run Intergration Test
          shell: powershell
          timeout-minutes: 1
          run: |
            cd .\Team26\Code26\build\src\integration_testing\
            .\integration_testing.exe

        - name: Copy Builds
          shell: powershell
          run: |
            mkdir artifacts
            cp .\Team26\Code26\build\src\autotester\autotester.exe .\artifacts\autotester.exe
            cp .\Team26\Code26\build\src\unit_testing\unit_testing.exe .\artifacts\unit_testing.exe
            cp .\Team26\Code26\build\src\integration_testing\integration_testing.exe .\artifacts\integration_testing.exe

        - name: Upload Builds
          uses: actions/upload-artifact@v2
          with:
            name: build-artifacts
            path: .\artifacts
