name: CI for Cmake Project - Windows

on: [pull_request]

jobs:
  checkstyle:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v3

      - name: Run Linter
        run: |
          cd .\Team26\Code26\src\spa
          cpplint --recursive --filter=-legal/copyright,-runtime/references --linelength=120 extensions=cpp,h .
  build:
      runs-on: [self-hosted, Windows, X64]
      timeout-minutes: 10
      strategy:
        fail-fast: true

      steps:
        - uses: actions/checkout@v3
        - name: Build Project
          shell: powershell
          run: |
            cd .\Team26\Code26
            mkdir build
            cd build
            cmake ..
            cmake --build . --target unit_testing --config Release
            cmake --build . --target autotester --config Release
            cd ../..
        - name: Run Unit Test
          shell: powershell
          timeout-minutes: 1
          run: |
            cd .\Team26\Code26\build\src\unit_testing\Release\
            .\unit_testing.exe

        - name: Run Autotester
          shell: powershell
          timeout-minutes: 1
          run: |
            cd .\Team26\Code26\build\src\autotester\Release\
            .\autotester.exe ..\..\..\..\..\Tests26\Week5_Demo\Sample_source.txt ..\..\..\..\..\Tests26\Week5_Demo\Sample_queries.txt ..\..\..\..\..\Tests26\Week5_Demo\out.xml
