name: CI for Cmake Project - MacOS (Cron)

on:
  schedule:
    - cron: "0 15,23 * * *"
  
  workflow_dispatch:     
    branches:     
      - "*"

env:
    BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/Team26/Code26/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/Team26/Code26/build
        run: cmake $GITHUB_WORKSPACE/Team26/Code26/ -G Ninja

      - name: Build Project
        shell: bash
        working-directory: ${{runner.workspace}}/Team26/Code26/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Unit Testing
        working-directory: ${{runner.workspace}}/Team26/Code26/build/src/unit_testing
        shell: bash
        run: ./unit_testing

      - name: Intergration Testing
        working-directory: ${{runner.workspace}}/Team26/Code26/build/src/integration_testing
        shell: bash
        run: ./integration_testing

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
          
      - name: Install cpplint
        run: pip install cpplint

      - name: Run Linter
        run: |
          cd Team26/Code26/src/spa
          cpplint --recursive --filter=-legal/copyright,-runtime/references --linelength=120 extensions=cpp,h .
