name: CI for Cmake Project - MacOS (Cron)

on:
  schedule:
    - cron: "0 15,23 * * *"
  
  workflow_dispatch:     
    branches:     
      - master

env:
    BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 3
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team26/Code26/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
          
      - name: Install cpplint
        run: pip install cpplint

      - name: Run Linter
        run: |
          cd Team26/Code26/src/spa
          cpplint --recursive --filter=-legal/copyright,-runtime/references --linelength=120 extensions=cpp,h .
